# Generated by Django 5.2.7 on 2025-10-23 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "official_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("country_code", models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sport",
                    models.ForeignKey(
                        db_column="_sport_foreignkey",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competitions",
                        to="events.sport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "competition",
                    models.ForeignKey(
                        db_column="_competition_foreignkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="events.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering"],
                "unique_together": {("name", "competition")},
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "scheduled"),
                            ("played", "played"),
                            ("cancelled", "cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("season", models.PositiveIntegerField(blank=True, null=True)),
                ("home_goals", models.PositiveIntegerField(blank=True, null=True)),
                ("away_goals", models.PositiveIntegerField(blank=True, null=True)),
                ("result_details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        db_column="_stage_foreignkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.stage",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        blank=True,
                        db_column="_away_team_foreignkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="away_events",
                        to="events.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        blank=True,
                        db_column="_home_team_foreignkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_events",
                        to="events.team",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        db_column="_winner_foreignkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wins",
                        to="events.team",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        db_column="_venue_foreignkey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["start_datetime"],
                "indexes": [
                    models.Index(
                        fields=["start_datetime"], name="events_even_start_d_b72861_idx"
                    ),
                    models.Index(
                        fields=["season"], name="events_even_season_1fcc8b_idx"
                    ),
                ],
            },
        ),
    ]
