# Generated by Django 5.2.7 on 2025-10-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_result_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
